local keymap = vim.keymap

vim.g.mapleader = " "
keymap.set("n", "<leader>w", ":w<CR>", { desc = "Write file" })
keymap.set("n", "<leader>q", ":q<CR>", { desc = "Quit Neovim" })
keymap.set({ "n", "v" }, "<leader>y", '"*y')
keymap.set({ "n", "v" }, "<leader>p", '"*p')
keymap.set({ "n", "v" }, "<leader>o", ":update<CR> :source<CR>")
keymap.set("n", "<C-h>", "<C-w>h", { desc = "Left window" })
keymap.set("n", "<C-j>", "<C-w>j", { desc = "Below window" })
keymap.set("n", "<C-k>", "<C-w>k", { desc = "Above window" })
keymap.set("n", "<C-l>", "<C-w>l", { desc = "Right window" })
keymap.set("n", "<leader>nh", ":nohl<CR>", { desc = "Clear search highlights" })
keymap.set("n", "gd", vim.lsp.buf.definition, { silent = true, noremap = true, desc = "Go to definition" })
keymap.set("n", "K", vim.lsp.buf.hover, { noremap = true, silent = true, desc = "Display prototype" })
keymap.set("n", "<leader>f", ":Pick files<CR>")
keymap.set("n", "<leader>h", ":Pick help<CR>")
keymap.set("n", "<leader>e", ":Oil<CR>")
keymap.set("n", "<leader>sv", "<C-w>v", { desc = "Split the window vertically" })
keymap.set("n", "<leader>sh", "<C-w>s", { desc = "Split the window horizontally" })
keymap.set("n", "<leader>sc", "<cmd>close<CR>", { desc = "Close the current split" })
keymap.set("n", "<leader>to", "<cmd>tabnew<CR>", { desc = "Open a new tab" })
keymap.set("n", "<leader>tc", "<cmd>tabclose<CR>", { desc = "Close current tab" })
keymap.set("n", "<leader>tn", "<cmd>tabn<CR>", { desc = "Close to the next tab" })
keymap.set("n", "<leader>tp", "<cmd>tabp<CR>", { desc = "Close to the previous tab" })
keymap.set("n", "<leader>do", ":DiffviewOpen<CR>", { desc = "Open GitDiff" })
keymap.set("n", "<leader>dc", ":DiffviewClose<CR>", { desc = "Close GitDiff" })
keymap.set("n", "<leader>lf", vim.lsp.buf.format, { desc = "Format the current file" })
keymap.set("n", "<leader>gl", function()
    require("gitgraph").draw({}, { all = true, max_count = 5000 })
end, { desc = "GitGraph - Draw" })
